// GENERATED by tool/blender/render_building.py (via renderall). Do not
// edit by hand — re-render and it is rewritten.
//
// Where each bundled picture's FOOTPRINT sits inside it, because the two
// are not the same rectangle: the render frame opens out to hold a roof, a
// spire or a castle wing leaning past the tile it stands on, and the app
// has to put the art back by its base rather than by its edges. See
// artPlacement() in data/iso_grid.dart for what the three mean.
library;

/// (artBaseWidth, artAnchorX, artLift), keyed by building def id.
const Map<String, (double, double, double)> kBundledArtBox = {
  'breeding_hut': (0.98483, 0.49241, 0.00000),
  'builder_camp': (1.00000, 0.50000, 0.00000),
  'caravanserai': (0.96933, 0.48466, 0.00000),
  'castle': (1.00000, 0.50000, 0.00000),
  'church': (1.00000, 0.50000, 0.00250),
  'gold_vault': (0.88113, 0.50000, 0.00000),
  'hatchery': (0.99404, 0.50298, 0.00000),
  'healing_hut': (0.95843, 0.47921, 0.00000),
  'large_house': (1.00000, 0.50000, 0.00000),
  'large_stone_camp': (1.00000, 0.50000, 0.00000),
  'large_wood_camp': (1.00000, 0.50000, 0.00000),
  'lux_fish': (1.00000, 0.50000, 0.02075),
  'lux_fur': (0.95855, 0.47928, 0.00000),
  'marketplace': (1.00000, 0.50000, 0.00250),
  'refinery_e2': (1.00000, 0.50000, 0.00000),
  'scout_post': (1.00000, 0.50000, 0.00000),
  'small_house': (1.00000, 0.50000, 0.00000),
  'small_stone_camp': (1.00000, 0.50000, 0.00000),
  'small_wood_camp': (1.00000, 0.50000, 0.00000),
  'storehouse': (1.00000, 0.50000, 0.00000),
  'thinker_circle': (1.00000, 0.50000, 0.00000),
  'trading_post': (0.98542, 0.50000, 0.00000),
  'training_grounds': (1.00000, 0.50000, 0.00000),
};
