// GENERATED by tool/blender/terrain.py — do not edit by hand.
//
// The same classify() that drew assets/images/map_background.png
// wrote this, so the coastline you can SEE and the coastline you can
// BUILD against are one thing. Re-render the background and this file
// is rewritten with it; edit this file alone and the two immediately
// disagree, which is the whole failure it exists to prevent.
//
// 3003 water cells of 24000.

/// Water, row by row, as flat [start, end) column pairs. Row y is
/// index y.
const List<List<int>> kWaterRuns = [
  [0, 15],
  [0, 15],
  [0, 15],
  [0, 16],
  [0, 16],
  [0, 17],
  [0, 17],
  [0, 18],
  [0, 18],
  [0, 18],
  [0, 18],
  [0, 19],
  [0, 19],
  [0, 19],
  [0, 19],
  [0, 19],
  [0, 20],
  [0, 20],
  [0, 20],
  [0, 20],
  [0, 19],
  [0, 19],
  [0, 19],
  [0, 19],
  [0, 19],
  [0, 19],
  [0, 18],
  [0, 18],
  [0, 18],
  [0, 17],
  [0, 17],
  [0, 17],
  [0, 16],
  [0, 16],
  [0, 15],
  [0, 15],
  [0, 14, 144, 150],
  [0, 14, 137, 156],
  [0, 13, 133, 160],
  [0, 13, 130, 163],
  [0, 12, 127, 166],
  [0, 12, 125, 168],
  [0, 11, 123, 139, 150, 170],
  [0, 11, 121, 135, 155, 172],
  [0, 11, 119, 131, 158, 174],
  [0, 10, 117, 129, 161, 176],
  [0, 10, 115, 126, 163, 177],
  [0, 9, 114, 124, 165, 179],
  [0, 9, 112, 122, 167, 180],
  [0, 9, 111, 120, 169, 182],
  [0, 9, 109, 119, 170, 183],
  [0, 8, 108, 117, 172, 185],
  [0, 8, 106, 115, 173, 186],
  [0, 8, 105, 114, 175, 187],
  [0, 8, 103, 112, 176, 189],
  [0, 8, 102, 111, 178, 190],
  [0, 8, 101, 110, 179, 191],
  [0, 8, 99, 108, 180, 193],
  [0, 8, 98, 107, 181, 194],
  [0, 8, 96, 105, 183, 195],
  [0, 8, 95, 104, 184, 196],
  [0, 8, 94, 103, 185, 197],
  [0, 8, 92, 102, 186, 199],
  [0, 8, 91, 100, 187, 200],
  [0, 9, 89, 99, 189, 200],
  [0, 10, 88, 98, 190, 200],
  [0, 12, 87, 96, 191, 200],
  [0, 13, 85, 95, 192, 200],
  [0, 14, 84, 94, 193, 200],
  [0, 16, 82, 92, 195, 200],
  [0, 17, 81, 91, 196, 200],
  [0, 19, 79, 90, 197, 200],
  [0, 20, 77, 88, 198, 200],
  [0, 22, 76, 87, 199, 200],
  [0, 24, 74, 86],
  [0, 25, 72, 84],
  [0, 27, 70, 83],
  [0, 13, 14, 29, 68, 81],
  [0, 13, 15, 31, 66, 80],
  [0, 13, 17, 34, 63, 78],
  [0, 14, 18, 37, 60, 77],
  [0, 14, 20, 41, 56, 75],
  [0, 14, 21, 73],
  [0, 14, 23, 71],
  [0, 14, 25, 69],
  [0, 15, 27, 67],
  [0, 15, 30, 65],
  [0, 15, 32, 62],
  [0, 15, 36, 59],
  [0, 15, 40, 54],
  [0, 15],
  [0, 15],
  [0, 15],
  [0, 15],
  [0, 15],
  [0, 15],
  [0, 15],
  [0, 14],
  [0, 14],
  [0, 14],
  [0, 14],
  [0, 13],
  [0, 13],
  [0, 13],
  [0, 12],
  [0, 12],
  [0, 11],
  [0, 11],
  [0, 10],
  [0, 10],
  [0, 10],
  [0, 9],
  [0, 9],
  [0, 8],
  [0, 8],
  [0, 7],
  [0, 7],
  [0, 7],
  [0, 6],
  [0, 6],
];

/// True when (x, y) is sea or river — the cells the settlement may
/// not build on (user 2026-08-09: "Der Fluss ist nicht bebaubar").
///
/// Off-map counts as NOT water: callers already range-check, and
/// answering "yes, water" for a cell that does not exist would quietly
/// turn every out-of-bounds bug into a placement refusal instead of an
/// error.
bool isWaterCell(int x, int y) {
  if (y < 0 || y >= kWaterRuns.length || x < 0) return false;
  final row = kWaterRuns[y];
  for (var i = 0; i < row.length; i += 2) {
    if (x >= row[i] && x < row[i + 1]) return true;
  }
  return false;
}
